"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _allmesocycle from './allmesocycle.bones.json'

registerBones({
  "allmesocycle": _allmesocycle,
})
